sudo: required
language: java

services:
  - docker

script:
  - ls
  - git clone -b develop https://cuitaocrazy:cuitao800505@gitee.com/yada-kitten/shouftOfficialWebsite.git
  - cd shouftOfficialWebsite
  - mvn package
  - cd ..
  - docker build -t cuitaocrazy/shouft:latest .
