sudo: required
language: java

script:
  - ls
  - mkdir sl
  - cd sl
  - git clone -b develop https://cuitaocrazy:cuitao800505@gitee.com/yada-kitten/shouftOfficialWebsite.git
  - cd shouftOfficialWebsite
  - mvn package
