spring:
  thymeleaf:
    cache: false
  datasource:
    ##引用自己的mysql
    url: jdbc:mysql://localhost:3306/btg?serverTimezone=UTC
    username: btg
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      default-auto-commit: true
      init-sql: select 1 from dual
      max-active: 128
      max-idle: 10
      max-wait: 5000
      min-evictable-idle-time-millis: 1800000
      test-on-borrow: true
      time-between-eviction-runs-millis: 900000
      validation-query: select 1 from dual
      validation-query-timeout: 2
  jpa:
    hibernate:
      ##validate  加载hibernate时，验证创建数据库表结构
      ##create   每次加载hibernate，重新创建数据库表结构，这就是导致数据库表数据丢失的原因。
      ##create-drop        加载hibernate时创建，退出是删除表结构
      ##update                 加载hibernate自动更新数据库结构
      ##validate 启动时验证表的结构，不会创建表
      ##none  启动时不做任何操作
      ddl-auto: none
    show-sql: true
  cache:
    type: ehcache
logging:
  level:
    root: info
  file:
    max-size: 400MB
    name: C:\home\websrv\log\officical\base.log
    max-history: 7
  pattern:
    rolling-file-name: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.log
server:
  servlet:
    context-path: /btgweb
  port: 8180
  #取磁盘下的图片
  #imgPath是实际图片存储的路径前缀，配置到upload目录
  #imgPre是图片访问需要添加的前缀，需要修改为正确的ip端口上下文根
img:
  imgPath: file:C://img/
  imgPre: http://127.0.0.1:8180/btgweb/img
connCard:
  sendDataToOut: http://localhost:8090/cardSystem/
  connectTimeout: 10000
  readTimeout: 100000
  connectionRequestTimeout: 10000
  maxConnTotal: 64
  maxConnPerRoute: 64
#程序中用到的展示信息
#公共展示信息
comm.errorMsg: 系统错误
comm.cardNoNotExist: 卡号不存在
comm.pwdVerifyError: 密码必须是6位数字
comm.remarksVerifyError: 备注不能为空且不可超长,请重新输入备注
#非实名卡延期
delay.successMsg: 恭喜您，申请非实名卡延期操作成功
#实名卡挂失
lost.idNoErrorMsg: 证件号输入有误，请重新输入
lost.success: 已挂失
#官网访问卡类型不存在
merweb.errorMsg: 该页无法显示,请与系统管理员联系!
#卡消费记录查询时间格式
info.timeFormatErrorMsg: 时间格式不正确,请重新输入
#拼接地图url需要的参数
map:
  noMapPre: https://map.qq.com/?
  noType: marker
  noIsopeninfowin: 1
  noMarkertype: 1
  ref: 首付通
#参数配置
param:
  #静态资源
  staticRes:
    #底部菜单名称
    footName: FooterText
  #一级菜单
  menu:
    #首页菜单编码
    homeId: 87
    #新闻资讯菜单编码
    businessId: 60
    #新闻资讯菜单编码
    newsId: 74
    #不需要获取二级菜单信息的路径
    paths: /enterpriseWeChat,/mer/merDetail,/error,/globalError,/list/newsInfo,/home/index
